### ISSUE TITLE
RoaH as maintainer

### ISSUE THREAD

**Issue by kepler0** [AtomLinter/linter-erlc#7]
@RaoH has created an updated version of this linter at [RaoH/linter-erlang](https://github.com/RaoH/linter-erlang). He should maintain this one, so not to have duplicate linters on Atom Package Manager.

**Comment by steelbrain** [comment]
@k2b6s9j that link is broken

**Comment by k2b6s9j** [comment]
@steelbrain thanks. I spelt @RaoH's username wrong.

**Comment by JonGretar** [comment]
Think that would be a good idea. Busy schedule is holding me back. @RaoH are you listening?

**Comment by RaoH** [comment]
I'm listening, if you fell you don't have time then I can maintain it.

**Comment by JonGretar** [comment]
I think 2 erlang linters are not needed. 

Wondering if I should just put a deprecation notice on this project(linking to yours) and remove it from apm. Or if you would like to take over this project on this location. 

If you prefer to base it on your repo you might consider relocating it to the AtomLinter organization.

I think @hd-deman is one of the AtomLinter officials. He might have some ideas on how linters are merged.

**Comment by RaoH** [comment]
Hmm I think I prefer to base in on my repo. Think they are quite different on the implementation (mine being a first official atom package from me) and I know the structure better there.

But either way I can solve that continuing on this repo.

**Comment by JonGretar** [comment]
This is all up to you. I have no preference in this.

@hd-deman can you give him admin rights to the repo?

**Comment by steelbrain** [comment]
@AsaAyers ^
@JonGretar: @hd-deman hasn't been active lately.

**Comment by hd-deman** [comment]
done. RaoH welcome

**Comment by RaoH** [comment]
Thank you!

**Comment by eddwardo** [comment]
:beer: for making current linter compatible with new API.

**Comment by kepler0** [comment]
Closing due to @RaoH having commit and admin access to this repo. If he choses to maintain and code for it he may.
